theme = "gruvbox-material-transparent"

[editor]
true-color = true
mouse = false
line-number = "relative"
auto-pairs = false
rulers = [80]

[keys.normal]
C-g = [
  ":write-all",
  ":insert-output lazygit >/dev/tty",
  ":redraw",
  ":reload-all"
]

[keys.normal.space]
e = [
  ":sh rm -f /tmp/unique-file-h21a434",
  ":insert-output yazi '%{buffer_name}' --chooser-file=/tmp/unique-file-h21a434",
  ":insert-output echo \"x1b[?1049h\" > /dev/tty",
  ":open %sh{cat /tmp/unique-file-h21a434}",
  ":redraw"
]

[keys.normal.g]
q = ":reflow"

[keys.select.g]
q = ":reflow"
