[language-server]
zk-lsp = { command = "zk", args = [ "lsp" ] }

[[language]]
name = "markdown"
roots = [ ".zk" ]
language-servers = [ "zk-lsp" ]

[[language]]
name = "markdown"
auto-format = true
formatter = { command = "prettier", args = ["--parser", "markdown"] }

[[language]]
name = "go"
auto-format = true
formatter = { command = "goimports" }
