[language-server]
zk-lsp = { command = "zk", args = [ "lsp" ] }

[[language]]
name = "markdown"
roots = [ ".zk" ]
language-servers = [ "zk-lsp" ]

[[language]]
name = "markdown"
auto-format = true
formatter = { command = "prettier", args = ["--parser", "markdown"] }

[[language]]
name = "go"
auto-format = true
formatter = { command = "goimports" }

[[language]]
name = "c"
file-types = ["c", "h"]
formatter = { command = 'clang-format' }
auto-format = true

[[language]]
name = "cpp"
file-types = ["cpp", "cc", "cxx", "hpp", "hcc", "hxx"]
formatter = { command = 'clang-format' }
auto-format = true
