[language-server]
zk-lsp = { command = "zk", args = [ "lsp" ] }

[[language]]
name = "markdown"
roots = [ ".zk" ]
language-servers = [ "zk-lsp" ]

[[language]]
name = "markdown"
formatter = { command = 'prettier', args = ["--parser", "markdown"] }
auto-format = true
